# Generated by Django 5.2.5 on 2025-09-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_referral_referralcampaign_referralstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralreward',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='accounts.referral'),
        ),
    ]
