# Generated by Django 4.2.7 on 2025-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_sellerbankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerbankdetails',
            name='ifsc_code',
            field=models.CharField(max_length=15),
        ),
    ]
