# Generated by Django 5.2.5 on 2025-09-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordertracking_courier_name_ordertracking_tracking_id'),
        ('payments', '0003_update_ifsc_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_shipping_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders_processed', models.PositiveIntegerField(default=0)),
                ('total_credits_sold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_admin_wallet',
            },
        ),
        migrations.CreateModel(
            name='AdminWalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('platform_fee', 'Platform Fee'), ('shipping_fee', 'Shipping Fee'), ('tax_amount', 'Tax Amount'), ('credit_purchase', 'Credit Purchase Revenue'), ('withdrawal', 'Admin Withdrawal'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('platform_fee', 'Platform Fee'), ('shipping_fee', 'Shipping Fee'), ('tax_amount', 'Tax Amount'), ('credit_purchase', 'Credit Purchase Revenue'), ('product_sale', 'Product Sale'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='credit_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.creditpurchase'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='Order number, payment ID, etc.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='payments_wa_wallet__1a003d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'category'], name='payments_wa_wallet__731a57_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='payments_wa_created_a3d6ca_idx'),
        ),
        migrations.AddField(
            model_name='adminwallethistory',
            name='admin_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.adminwallet'),
        ),
        migrations.AddField(
            model_name='adminwallethistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminwallethistory',
            name='credit_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.creditpurchase'),
        ),
        migrations.AddField(
            model_name='adminwallethistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='adminwallethistory',
            index=models.Index(fields=['transaction_type'], name='payments_ad_transac_2c8a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallethistory',
            index=models.Index(fields=['created_at'], name='payments_ad_created_a919d7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallethistory',
            index=models.Index(fields=['order'], name='payments_ad_order_i_8ab813_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallethistory',
            index=models.Index(fields=['credit_purchase'], name='payments_ad_credit__688936_idx'),
        ),
    ]
