# Generated by Django 5.2.5 on 2025-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_adminwallet_adminwallethistory_and_more'),
    ]

    operations = [
    ]
