# Generated by Django 4.2.7 on 2025-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='last_credit_deduction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='livestreams/thumbnails/'),
        ),
    ]
