# Generated by Django 5.2.5 on 2025-09-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0002_livestream_last_credit_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='auto_end_warned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
